version: "3.8"
services:
  app:
    build:
      context: .
    # environment:
    #   - NODE_ENV=production
    volumes:
      - ./src:/app
      - /app/node_modules
    ports:
      - "3333:3333"

  mongodb:
    image: mongo:4
    command: mongod
    ports:
      - "27017:27017"
