name: CAPJu Service CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download dependencies
        run: cd src && yarn && cd ..
      - name: Check code style
        run: cd src && yarn prettier --check . && cd ..
      - name: Lint Analysis
        run: cd src && yarn eslint . && cd ..
      - name: Building docker-compose stack
        run: docker-compose up -d
      - name: Check running containers
        run: docker ps -a
      - name: Run test suite
        run: docker-compose exec -T app yarn test
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup ssh key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: run
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} "cd app && docker-compose up --build -d"
